export * from './components';
export * from './theme';

// Re-export commonly used MUI components for convenience
import {
  ThemeProvider,
  CssBaseline,
  Box,
  Container,
  Grid,
  Stack,
  Paper,
  Card,
  CardContent,
  CardActions,
  CardHeader,
  Typography,
  Button,
  IconButton,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  ListItemButton,
  Divider,
  Chip,
  Avatar,
  useTheme,
  useMediaQuery,
} from '@mui/material';
import { styled } from '@mui/material/styles';

export {
  ThemeProvider,
  CssBaseline,
  Box,
  Container,
  Grid,
  Stack,
  Paper,
  Card,
  CardContent,
  CardActions,
  CardHeader,
  Typography,
  Button,
  IconButton,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  ListItemButton,
  Divider,
  Chip,
  Avatar,
  useTheme,
  useMediaQuery,
  styled,
};

export type { Theme, PaletteMode, SxProps } from '@mui/material';
